name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # The whole Node.js and pnpm installation and caching
      # Based on https://github.com/pnpm/action-setup/tree/6e1964dde3397a825e79e4607ad57f3f7ca2c7cb#use-cache-to-reduce-installation-time

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Svelte Check
        if: success() || failure() # Run even if previous failed
        run: npm run check
      
      # Build Frontend
      - name: Build Frontend
        if: success() || failure() # Run even if previous failed
        run: npm run build
      
      # Setup Nuget and install IE11 web driver
      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1
      - name: Install IE11 Web Driver
        run: nuget install Selenium.WebDriver.IEDriver -Version 4.5.0
      
      # Run Selenium Tests
      - name: Test
        run: npm run preview & npm run test-selenium
        env:
          DEBUG: pw:webserver
